#pragma once

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define ANALOG_JOYSTICK_X_AXIS_PIN B4
#define ANALOG_JOYSTICK_Y_AXIS_PIN B5
#define ANALOG_JOYSTICK_SPEED_REGULATOR 8
#define ANALOG_JOYSTICK_SPEED_MAX 5
